name: Build DLL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Download Resonite
      shell: pwsh
      run: |
        [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
        $webClient = New-Object System.Net.WebClient
        $webClient.DownloadFile("https://clouddelivery.resonite.com/BuildData/Live/Windows/Resonite.zip", "Resonite.zip")
        Expand-Archive -Path "Resonite.zip" -DestinationPath "Resonite"
        
    - name: Download ResoniteModLoader
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/resonite-modding-group/ResoniteModLoader/releases/latest/download/ResoniteModLoader.dll" -OutFile "Resonite/Libraries/ResoniteModLoader.dll"
        New-Item -ItemType Directory -Force -Path "Resonite/rml_libs"
        Invoke-WebRequest -Uri "https://github.com/resonite-modding-group/ResoniteModLoader/releases/latest/download/0Harmony.dll" -OutFile "Resonite/rml_libs/0Harmony.dll"
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CustomPlatformColors-DLL
        path: CustomPlatformColors/bin/Release/net*/CustomPlatformColors.dll